CONSUMER_KEY = "FKUCGd0vcCL5vi6CaYFn9TJmf"
CONSUMER_SECRET = "MGxOWwJUZMBQAef1XJbrbKNJisbHNu26bsKErHSczbf5R3kRtJ"
ACCESS_KEY = "1315998691430469634-2VJAlB3qp7HZsCxt3gFt8G0mx8Ep5N"
ACCESS_SECRET = "I7EfvNgBBPIg7A5hK6PuxuBnZZeHPi09kCGW7iG3rbnzt"
Github_username = "farhanfadilla"
Github_password = "M4nchestercity123"
Github_repo = "farhanfadilla/Database_UINJKTFESS" #use another repo instead of primary repo
First_Keyword = "-uwin" #primary keyword for tweet, vide, and image
Second_Keyword = "[quote]" #for make image quoted
Sub2_Keyword = "-s" #give image quoted name
Third_keyword = "[tamin]" #ask admin
Admin_id = "farhan_fadillaa"
timezone = 7
